sugar_p/urls.py
""" Определяет схемы URL для sugar_p."""

from django.urls import path
from django.views.generic.base import TemplateView

from . import views
from django.contrib.sitemaps.views import sitemap
from sugar_p.sitemap import DynamicViewSitemap, StaticViewSitemap, StaticMainViewSitemap, DynamicTagViewSitemap

sitemaps = {
	'static': StaticViewSitemap,
	'static_main': StaticMainViewSitemap,
	'dynamic_tag': DynamicTagViewSitemap,
	'dynamic': DynamicViewSitemap
}

app_name = 'sugar_p'
urlpatterns = [
	# Домашняя страница
	path('', views.index, name='index'),
	# Страница со списком аниме
	path('anime/', views.animes, name='animes'),
	path('search/', views.search, name='search'),
	path('anime/genre/<slug:tag_slug>/', views.animes_by_genre, name='animes_by_tag'),
	path('anime/<slug:anime_slug>/', views.anime, name='anime'),
	path('anime/top-50', views.top_fifteen, name='top_fifteen'),
	path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
	path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"))
]

sugar_prince/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('sugar_p.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sugar_p/models.py
from django import views
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from .ru_taggit import RuTaggedItem

class Ip(models.Model): # наша таблица где будут айпи адреса
	ip = models.CharField(max_length=100)

	def __str__(self):
 		return self.ip

class Anime(models.Model):
	"""Аниме и информация о ней"""
	title = models.CharField(max_length=255, verbose_name="Название")
	slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
	poster = models.ImageField(upload_to='imgs', verbose_name="Постер")
	date_added = models.DateField(auto_now_add=True, verbose_name="Дата")
	desc = models.TextField(verbose_name="Описание", blank=True, default="")
	source = models.TextField(verbose_name="Ссылка iframe")
	tags = TaggableManager(through=RuTaggedItem, verbose_name='Жанры')
	views = models.ManyToManyField(Ip, related_name="anime_views", blank=True)

	def __str__(self):
		return self.title
	
	def total_views(self):
		return self.views.count()

	def get_absolute_url(self):
		return reverse('anime', kwargs={'anime_slug': self.slug})

	class Meta:
		verbose_name = "Аниме"
		verbose_name_plural = 'Аниме'

sugar_p/views.py
from django.shortcuts import render
from .models import Anime, Ip
from taggit.models import Tag
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from random import sample

def random_animes(anime):
	"""Возвращает 3 рандомные аниме"""
	try:
		my_ids = anime.objects.values_list('id', flat=True)
		my_ids = list(my_ids)
	except:
		return None
	if len(my_ids) == 1:
		return anime.objects.all()
	if len(my_ids) == 2:
		return anime.objects.all()
	rand_ids = sample(my_ids, 3)
	random_animes = anime.objects.filter(id__in=rand_ids)
	return random_animes

def get_client_ip(request):
	"""Получает IP и возвращает его"""
	x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
	if x_forwarded_for:
		ip = x_forwarded_for.split(',')[0]
	else:
		ip = request.META.get('REMOTE_ADDR')
	return ip

def index(request):
	"""Домашняя страница приложения Sugar Prince"""
	random_anime = random_animes(Anime)
	context = {'random_animes': random_anime}
	return render(request, 'sugar_p/index.html', context)

def animes(request, tag_slug=None):
	"""Выводит список аниме"""
	animes = Anime.objects.order_by('-date_added')
	tag = None
	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug) 
		animes = animes.filter(tags__in=[tag])

	page = request.GET.get('page')
	paginator = Paginator(animes, 20)
	try:
		animes = paginator.page(page)
	except PageNotAnInteger:
		try:
			animes = paginator.page(1)
		except:
			animes = None
	except EmptyPage:
		animes = paginator.page(paginator.num_pages)
	random_anime = random_animes(Anime)
	all_tags = Tag.objects.all()
	context = {'animes': animes, 'page': page, 'tag': tag, 'random_animes': random_anime,
														'all_tags': all_tags}
	return render(request, 'sugar_p/animes.html', context)

def animes_by_genre(request, tag_slug=None):
	"""Выводит список аниме"""
	animes = Anime.objects.order_by('-date_added')
	tag = None
	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug) 
		animes = animes.filter(tags__in=[tag])

	page = request.GET.get('page')
	paginator = Paginator(animes, 20)
	try:
		animes = paginator.page(page)
	except PageNotAnInteger:
		animes = paginator.page(1)
	except EmptyPage:
		animes = paginator.page(paginator.num_pages)
	random_anime = random_animes(Anime)
	all_tags = Tag.objects.all()
	context = {'animes': animes, 'page': page, 'tag': tag, 'random_animes': random_anime,
														'all_tags': all_tags}
	return render(request, 'sugar_p/animesgenre.html', context)

def search(request):
	"""Выводит список аниме по запросу в поисковике"""
	search_query = request.GET.get("q")

	if search_query == None:
		animes = Anime.objects.order_by('-date_added')
	else:
		animes = Anime.objects.filter(title__icontains=search_query).order_by('-date_added')

	page = request.GET.get('page')
	paginator = Paginator(animes, 2)
	try:
		# try:
			animes = paginator.page(page)
		# except:
		# 	animes = None
	except PageNotAnInteger:
		animes = paginator.page(1)
	except EmptyPage:
		animes = paginator.page(paginator.num_pages)
	
	all_tags = Tag.objects.all()
	random_anime = random_animes(Anime)
	context = {'animes': animes, 'page': page, 'search_q': search_query,
							'random_animes': random_anime, 'all_tags': all_tags}
	return render(request, 'sugar_p/search.html', context)

def anime(request, anime_slug):
	"""Выводит аниме"""
	anime = get_object_or_404(Anime, slug=anime_slug)

	ip = get_client_ip(request)

	if Ip.objects.filter(ip=ip).exists():
		anime.views.add(Ip.objects.get(ip=ip))
	else:
		Ip.objects.create(ip=ip)
		anime.views.add(Ip.objects.get(ip=ip))
	random_anime = random_animes(Anime)
	context = {'anime': anime, 'random_animes': random_anime}
	return render(request, 'sugar_p/anime.html', context)

def top_fifteen(request):
	"""Выводит топ 50 аниме"""
	animes = Anime.objects.order_by('-views')[:50]
	page = request.GET.get('page')
	paginator = Paginator(animes, 20)
	try:
		try:
			animes = paginator.page(page)
		except:
			animes = None
	except PageNotAnInteger:
		animes = paginator.page(1)
	except EmptyPage:
		animes = paginator.page(paginator.num_pages)
	random_anime = random_animes(Anime)
	random_anime = None
	all_tags = Tag.objects.all()
	context = {'animes': animes, 'page': page, 'random_animes': random_anime,
														'all_tags': all_tags}
	return render(request, 'sugar_p/top_fifteen.html', context)

sugar_p/templates/sugar_p/animes.html
{% extends 'sugar_p/base.html' %}
{% load static %}

{% block desc %}<meta name="description" content="Все аниме на любой вкус и жанр. Ты точно найдешь, что искал">{% endblock desc %}
{% block title %}Все аниме{% endblock title %}

{% block content %}
	<div class="wrapper">
		<div class="animes">
			<div class="title__animes">
				<div class="title__list">
					{% if tag %}
					<h1 class="title__anime-all">
						Аниме:<span class="title__anime-tag">{{ tag.name }}</span>
					</h1>
					{% else %}
					<h1 class="title__anime-all">
						Все аниме
					</h1>
					{% endif %}
				</div>
				<p class="tags">
					Жанры:
					{% if all_tags %}
						{% for tag in all_tags %}
						<a href="{% url 'sugar_p:animes_by_tag' tag.slug %}" class="tag-title">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
						{% endfor %}
					{% else %}
						<h3>Ещё не добавлены жанры</h3>
					{% endif %}
				</p>
			</div>
			<ul class="anime_list infinite-container">
				{% if anime %}
				{% for anime in animes %}
					<li class="anime__list-item infinite-item">
						<a href="{% url 'sugar_p:anime' anime.slug %}" class="anime-item anime__img">
							<img src="{{ anime.poster.url }}" alt="{{ anime.title }}" class="list__poster-pic">
						</a>
						<div class="anime-item anime__info">
							<a href="{% url 'sugar_p:anime' anime.slug %}" class="anime-link">{{ anime.title }}</a>
							<p class="tags">
							{% for tag in anime.tags.all %}
								<a href="{% url 'sugar_p:animes_by_tag' tag.slug %}" class="tag">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
							{% endfor %}
							</p>
							<p class="anime-desc">
								{{ anime.desc|truncatechars:450 }}
							</p>
						</div>
					</li>
				{% endfor %}
				{% else %}
					<h3>Ещё нет ни одного аниме</h3>
				{% endif%}
			</ul>
			{% if animes.has_next %}
				<a href="?page={{ animes.next_page_number }}" class="infinite-more-link"></a>
			{% endif %}
			<div class="loading" style="display: none;">
				Загрузка... Подожди немного
			</div>
		</div>
	</div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script>
	var infinite = new Waypoint.Infinite({
		element: $('.infinite-container')[0],
		offset: function () {
    		return this.context.innerHeight() - this.adapter.outerHeight() + 700
		},
		onBeforePageLoad: function () {
			$('.loading').show();
		},
		onAfterPageLoad: function ($items) {
			$('.loading').hide();
		}
	});
</script>
{% endblock scripts %}

sugar_p/templates/sugar_p/animesgenre.html
{% extends 'sugar_p/base.html' %}
{% load static %}

{% block desc %}<meta name="description" content="Все аниме на любой вкус и жанр. Ты точно найдешь, что искал">{% endblock desc %}
{% block title %}Все аниме жанра {{tag.name}}{% endblock title %}

{% block content %}
	<div class="wrapper">
		<div class="animes">
			<div class="title__animes">
				<div class="title__list">
					{% if tag %}
					<h1 class="title__anime-all">
						Аниме:<span class="title__anime-tag">{{ tag.name }}</span>
					</h1>
					{% else %}
					<h1 class="title__anime-all">
						Все аниме
					</h1>
					{% endif %}
				</div>
				<p class="tags">
					Жанры:
					{% for tag in all_tags %}
						<a href="{% url 'sugar_p:animes_by_tag' tag.slug %}" class="tag-title">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
					{% endfor %}
				</p>
			</div>
			<ul class="anime_list infinite-container">
				{% for anime in animes %}
					<li class="anime__list-item infinite-item">
						<a href="{% url 'sugar_p:anime' anime.slug %}" class="anime-item anime__img">
							<img src="{{ anime.poster.url }}" alt="{{ anime.title }}" class="list__poster-pic">
						</a>
						<div class="anime-item anime__info">
							<a href="{% url 'sugar_p:anime' anime.slug %}" class="anime-link">{{ anime.title }}</a>
							<p class="tags">
							{% for tag in anime.tags.all %}
								<a href="{% url 'sugar_p:animes_by_tag' tag.slug %}" class="tag">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
							{% endfor %}
							</p>
							<p class="anime-desc">
								{{ anime.desc|truncatechars:450 }}
							</p>
						</div>
					</li>
				{% endfor %}
			</ul>
			{% if animes.has_next %}
				<a href="?page={{ animes.next_page_number }}" class="infinite-more-link"></a>
			{% endif %}
			<div class="loading" style="display: none;">
				Загрузка... Подожди немного
			</div>
		</div>
	</div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script>
	var infinite = new Waypoint.Infinite({
		element: $('.infinite-container')[0],
		offset: function () {
    		return this.context.innerHeight() - this.adapter.outerHeight() + 700
		},
		onBeforePageLoad: function () {
			$('.loading').show();
		},
		onAfterPageLoad: function ($items) {
			$('.loading').hide();
		}
	});
</script>
{% endblock scripts %}

sugar_p/templates/sugar_p/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block desc %}{% endblock desc %}
	<meta name="keywords" content="Аниме, фильмы, анигири, anigiri">
	<title>{% block title %}{% endblock title %}</title> 
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
	<link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">
	<link rel="mask-icon" href="{% static 'img/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
	<link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}">
	<meta name="msapplication-TileColor" content="#603cba">
	<meta name="msapplication-config" content="img/favicon/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">
	<link rel="stylesheet" href="{% static 'css/boot.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles.min.css' %}">
	<link rel="stylesheet" href="{% static 'WOW-master/css/libs/animate.css' %}">
</head>
<body>
	<!-- Header start -->
	<header class="header">
		<div class="wrapper">
			<div class="header__wrapper">
				<div class="header__burger burger">
					<span class="burger__line burger__line_first"></span>
					<span class="burger__line burger__line_second"></span>
					<span class="burger__line burger__line_third"></span>
				</div>
				<div class="header__logo">
					<a href="{% url 'sugar_p:index' %}" class="header__logo-link">
						<img src="{% static 'img/svg/anigiri.svg' %}" alt="Смотреть аниме онлайн бесплатно в хорошем качестве" class="header__logo-pic">
					</a>
				</div>
				<nav class="header__nav">
					<form action="{% url 'sugar_p:search' %}" method="get" class="mobile__search d-flex" role="search">
						<div class="input-group group__search">
						  <input type="search" class="form-control border-primary" placeholder="Поиск" name="q" aria-label="Поиск" aria-describedby="button-addon2">
						  <button class="btn btn-outline-primary" type="submit" id="button-addon2">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
							  	<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
								</svg>
						  </button>
						</div>
					</form>
					<ul class="header__list">
						<li class="header__item">
							<a href="{% url 'sugar_p:animes' %}" class="header__link button button__header">
								<span class="button__line button__line--top"></span>
								<span class="button__line button__line--right"></span>
								<span class="button__line button__line--bottom"></span>
								<span class="button__line button__line--left"></span>
								Аниме
							</a>
						</li>
						<li class="header__item">
							<a href="{% url 'sugar_p:top_fifteen' %}" class="header__link button button__header">
								<span class="button__line button__line--top"></span>
								<span class="button__line button__line--right"></span>
								<span class="button__line button__line--bottom"></span>
								<span class="button__line button__line--left"></span>
								Топ 50 популярных
							</a>
						</li>
					</ul>
					<form action="{% url 'sugar_p:search' %}" method="get" class="d-flex desktop__search" role="search">
						<div class="input-group">
						  <input type="search" class="form-control border-primary" placeholder="Поиск" name="q" aria-label="Поиск" aria-describedby="button-addon2">
						  <button class="btn btn-outline-primary" type="submit" id="button-addon2">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
							  	<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
								</svg>
						  </button>
						</div>
					</form>
					<div class="header__nav-close">
						<span class="header__nav-close-line"></span>
						<span class="header__nav-close-line"></span>
					</div>
				</nav>
			</div>
		</div>
	</header>
	<!-- Header end -->
	<main class="main">
        {% block content %}{% endblock content %}
		<!-- Menu start -->
		<section class="menu wow fadeInUp">
			<div class="menu__wrap">
				<h2 class="menu__title">
					Случайные аниме
				</h2>
				{% if random_animes %}
				<div class="menu__cards">
						{% for random_anime in random_animes %}
						<div class="menu__card menu__card-size-lg">
							<img src="{{ random_anime.poster.url }}" alt="{{ random_anime.title }}" class="menu__card-img">
							<h3 class="menu__card-title">
								{{ random_anime.title }}
							</h3>
								<a href="{% url 'sugar_p:anime' random_anime.slug %}" class="menu__card-more"></a>
						</div>
						{% endfor %}
					</div>
				{% else %}
					<h3 style="color:white; font-size:25px">В БД должно быть минимум 3 аниме</h3>
				{% endif %}
			</div>
		</section>
		<!-- Menu end -->
	</main>

	<footer class="footer">
		<div class="wrapper">
			<div class="footer__item">
				<div class="footer__logo">
					<img src="{% static 'img/svg/anigiri-footer.svg' %}" alt="Смотреть аниме онлайн бесплатно в хорошем качестве" class="footer__logo-pic">
				</div>
				<nav class="footer__nav">
					<ul class="footer__menu">
						<li class="footer__menu-item">
							<p>theanigiri@gmail.com</p>
						</li>
					</ul>
					<ul class="footer__menu">
						<li class="footer__menu-item">
							<a href="https://vk.com/sugarprince" class="footer__menu-link">Вконтакте</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</footer>
	<script src="{% static 'js/main.min.js' %}"></script>
	<script src="{% static 'WOW-master/dist/wow.min.js' %}"></script>
	<script>
		new WOW().init();
	</script>
	{% block scripts %}{% endblock scripts %}
</body>
</html>

sugar_p/templates/sugar_p/search.html
{% extends 'sugar_p/base.html' %}
{% load static %}

{% block desc %}<meta name="description" content="Все аниме на любой вкус и жанр. Ты точно найдешь, что искал!">{% endblock desc %}
{% block title %}Поиск{% endblock title %}

{% block content %}
	<div class="wrapper">
		<div class="animes">
			<div class="title__animes">
				<div class="title__list-search">
					<h1 class="title__anime-all-search">
						Найти Аниме: <span class="title__anime-tag">{{ search_q }}</span>
					</h1>
					<form action="{% url 'sugar_p:search' %}" method="get" class="d-flex title__search desktop__search" role="search">
						<div class="input-group  title__inp">
						  <input type="search" value="{{ search_q }}"class="form-control border-primary" placeholder="Поиск" name="q" aria-label="Поиск" aria-describedby="button-addon2">
						  <button class="btn btn-outline-primary" type="submit" id="button-addon2">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
								  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
								</svg>
						  </button>
						</div>
					</form>
				</div>
				<p class="tags">
					Искать по жанру:
					{% if all_tags %}
						{% for tag in all_tags %}
						<a href="{% url 'sugar_p:animes_by_tag' tag.slug %}" class="tag-title">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
						{% endfor %}
					{% else %}
						<h3>Ещё не добавлены жанры</h3>
					{% endif %}
				</p>
			</div>
			<form action="{% url 'sugar_p:animes' %}" method="get" class="mobile__search d-flex" role="search">
				<div class="input-group group__search">
				  <input type="search" class="form-control border-primary" placeholder="Поиск" name="q" aria-label="Поиск" aria-describedby="button-addon2">
				  <button class="btn btn-outline-primary btn-search" type="submit" id="button-addon2">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
						  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
						</svg>
				  </button>
				</div>
			</form>
			<ul class="anime_list infinite-container">
				{% if animes %}
					{% for anime in animes %}
						<li class="anime__list-item infinite-item">
							<a href="{% url 'sugar_p:anime' anime.slug %}" class="anime-item anime__img">
								<img src="{{ anime.poster.url }}" alt="{{ anime.title }}" class="list__poster-pic">
							</a>
							<div class="anime-item anime__info">
								<a href="{% url 'sugar_p:anime' anime.slug %}" class="anime-link">{{ anime.title }}</a>
								<p class="tags">
								{% for tag in anime.tags.all %}
									<a href="{% url 'sugar_p:animes_by_tag' tag.slug %}" class="tag">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
								{% endfor %}
								</p>
								<p class="anime-desc">
									{{ anime.desc|truncatechars:450 }}
								</p>
							</div>
						</li>
					{% endfor %}
				{% else %}
					<p class="anime__list__null">
						Ничего не найдено по вашему запросу :(
						Возможно вы допустили ошибку в названии. Попробуйте поискать аниме <a href="{% url 'sugar_p:animes' %}" class="animes__link">здесь</a>.
					</p>
				{% endif %}
			</ul>
			{% if animes.has_next %}
				<a href="?page={{ animes.next_page_number }}" class="infinite-more-link"></a>
			{% endif %}
			<div class="loading" style="display: none;">
				Загрузка... Подожди немного
			</div>
		</div>
	</div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script>
	var infinite = new Waypoint.Infinite({
		element: $('.infinite-container')[0],
		offset: function () {
    		return this.context.innerHeight() - this.adapter.outerHeight() + 700
		},
		onBeforePageLoad: function () {
			$('.loading').show();
		},
		onAfterPageLoad: function ($items) {
			$('.loading').hide();
		}
	});
</script>
{% endblock scripts %}

sugar_p/templates/sugar_p/top_fifteen.html
{% extends 'sugar_p/base.html' %}
{% load static %}

{% block desc %}<meta name="description" content="Топ популярных аниме, которые могут понравится тебе">{% endblock desc %}
{% block title %}Топ 50 самых популярных аниме{% endblock title %}

{% block content %}
	<div class="wrapper">
		<div class="animes">
			<div class="title__animes">
				<div class="title__list">
					<h1 class="title__anime-all">
						Топ 50 популярных аниме
					</h1>
				</div>
				<p class="tags">
					Жанры:
					{% if all_tags %}
						{% for tag in all_tags %}
						<a href="{% url 'sugar_p:animes_by_tag' tag.slug %}" class="tag-title">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
						{% endfor %}
					{% else %}
						<h3>Ещё не добавлены жанры</h3>
					{% endif %}
				</p>
			</div>
			<ul class="anime_list infinite-container">
				{% if anime %}
				{% for anime in animes %}
					<li class="anime__list-item infinite-item">
						<a href="{% url 'sugar_p:anime' anime.slug %}" class="anime-item anime__img">
							<img src="{{ anime.poster.url }}" alt="{{ anime.title }}" class="list__poster-pic">
						</a>
						<div class="anime-item anime__info">
							<a href="{% url 'sugar_p:anime' anime.slug %}" class="anime-link">{{ anime.title }}</a>
							<p class="tags">
							{% for tag in anime.tags.all %}
								<a href="{% url 'sugar_p:animes_by_tag' tag.slug %}" class="tag">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
							{% endfor %}
							</p>
							<p class="anime-desc">
								{{ anime.desc|truncatechars:450 }}
							</p>
						</div>
					</li>
				{% endfor %}
				{% else %}
					<h3>Ещё нет ни одного аниме</h3>
				{% endif%}
			</ul>
			{% if animes.has_next %}
				<a href="?page={{ animes.next_page_number }}" class="infinite-more-link"></a>
			{% endif %}
			<div class="loading" style="display: none;">
				Загрузка... Подожди немного
			</div>
		</div>
	</div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script>
	var infinite = new Waypoint.Infinite({
		element: $('.infinite-container')[0],
		offset: function () {
    		return this.context.innerHeight() - this.adapter.outerHeight() + 700
		},
		onBeforePageLoad: function () {
			$('.loading').show();
		},
		onAfterPageLoad: function ($items) {
			$('.loading').hide();
		}
	});
</script>
{% endblock scripts %}